### ISSUE TITLE
External Meter AC Active Energy (NO SALE)

### ISSUE THREAD

**Issue by Hagory85** [vortizhe/home-assistant-ingeteam-modbus#1]
Buenas, en primer lugar Feliz Año... he estado trasteando la integración y es una pasada, lo único que no consigo ver el External Meter AC, ese dato no te lo proporciona... es viable introducirlo?
El estado del inversor tampoco lo saca, es viable sacarlo?

**Comment by vortizhe** [comment]
Comprobamos esto y efectivamente si que estaba saliendo pero no tenías seleccionado el external meter en la instalación del plugin.
