### ISSUE TITLE
Sensors with positive values for HomeAssistant

### ISSUE THREAD

**Issue by pmellenb** [vortizhe/home-assistant-ingeteam-modbus#2]
The Energy dashboard in HomeAssistant requires sensors with positive values. However, the ones provided by Ingeteam can have both positive and negative values. For instance, the battery power can be positive or negative for discharge and charge respectivelly.

It would be interesting to have new sensors with positive values only.

**Comment by jesus-chacon** [comment]
I have do a fork adding this functionality, for example you need it for tesla card
<img width="418" alt="Captura de pantalla 2023-01-04 a las 9 15 07" src="https://user-images.githubusercontent.com/6988778/210511864-21caa151-3df2-49ba-8f2a-16d320301cce.png">
<img width="1248" alt="Captura de pantalla 2023-01-04 a las 9 17 10" src="https://user-images.githubusercontent.com/6988778/210512313-abf55587-4d2a-4c63-b20e-d322d19926fd.png">

**Comment by vortizhe** [comment]
Added positive and negative values for critical loads power, external meter power, and battery charge/discharge power on https://github.com/vortizhe/home-assistant-ingeteam-modbus/commit/6688fa0665094539b22df70536c6f77f4963301d
