### ISSUE TITLE
wrong unit of measure in sensor

### ISSUE THREAD

**Issue by jantlopez** [vortizhe/home-assistant-ingeteam-modbus#3]
Hello Victor, I have detected an error in the sensor (sensor.ingeteam_critical_loads_active_power) that shows in AMPS and it should be in watts. Greetings and great job.

**Comment by vortizhe** [comment]
Fixed on https://github.com/vortizhe/home-assistant-ingeteam-modbus/commit/42cdcddb0ae90ad697680694848cccf8780d845a and released v0.1.2 version
