### ISSUE TITLE
Add sensor for register 30079 Total Loads. Active Power (critical + non-critical)

### ISSUE THREAD

**Issue by xenoncorp2k** [vortizhe/home-assistant-ingeteam-modbus#5]
Hello.

Could you incorporate reading the register 30079 Total Loads. Active Power (critical + non-critical) ?

It would be interesting to know the power of the total loads for which we have critical and non-critical loads without having to perform calculations.

Thank you for your magnificent work.

**Comment by vortizhe** [comment]
Added on last v0.3.0 release version https://github.com/vortizhe/home-assistant-ingeteam-modbus/releases/tag/v0.3.0.
