### ISSUE TITLE
Failed to use in conjunction with Victron Modbus integration

### ISSUE THREAD

**Issue by juanmijm** [vortizhe/home-assistant-ingeteam-modbus#6]
![image](https://github.com/vortizhe/home-assistant-ingeteam-modbus/assets/62819001/bca4bfc1-bccf-41bc-9198-f4e243e79b1c)
![image](https://github.com/vortizhe/home-assistant-ingeteam-modbus/assets/62819001/27907dc6-8418-44ff-abd1-32649cb8781f)

Hi I am trying to add the Victron integration from https://github.com/sfstar/hass-victron
but I can't get it to work, when I try to configure it, it gives me these errors, talking to the developer, he tells me that it is possible that there is an incompatibility with the modbus version used by another addon.

I don't know which of the two should correct it to solve this problem, that's why I have opened an issue for both of you, thank you very much.

**Comment by vortizhe** [comment]
Pymodbus was update on last release, please update and try it.

https://github.com/vortizhe/home-assistant-ingeteam-modbus/releases/tag/v0.3.0

**Comment by juanmijm** [comment]
wooow, updated and now everything is working, thank you very much, you are de best! :)
