### ISSUE TITLE
Add sensor for home compsumption

### ISSUE THREAD

**Issue by ulanda** [vortizhe/home-assistant-ingeteam-modbus#7]
With current entities the power-flow-card calculates the Home energy usage properly, but we cant have that data to be shown in a dashboard or into and horizontal-stack gauge
![IMG_0823](https://github.com/vortizhe/home-assistant-ingeteam-modbus/assets/3260081/5936695a-a773-4f2a-8f47-b93481b8954e)
![IMG_0824](https://github.com/vortizhe/home-assistant-ingeteam-modbus/assets/3260081/7ce38279-6944-48b7-a5be-1fdc31b44ccc)

**Comment by vortizhe** [comment]
There is no home comsumption provided by ingeteam api since it depends on each installation (external meter position, critical loads, etc). 

Try https://community.home-assistant.io/t/power-flow-card-plus/552326 cards has some improvements and calcs home consumption based on the other sensors.
