### ISSUE TITLE
Integration stopped working suddenly.

### ISSUE THREAD

**Issue by oscarrdg** [vortizhe/home-assistant-ingeteam-modbus#8]
I had this integration working reading information from some Ingeteam inverter a few months ago, but suddenly it stopped receiving any more data.

The inverter is still working in the network, as I can connect to it, and even get info via modbus through NodeRed.

But somehow, i am not able to get this integration to work again.
I've tried deleting the entity, completely deleting the integration, restarting HA, installing the integration, restarting HA, and configuring everything back again, but it's still not working.

The most frustrating is that I can not find anything in the logs.
If I try to connect to a wrong IP, I get the expected "timeout connecting". But when I use the correct inverter IP, I get no logs, but the ingeteam entities get no data: some of them are "unavailable" and others are "unknown".

I just found the following log, that I am not even sure it's related to this problem:

----
Logger: homeassistant.components.integration.sensor
Source: components/integration/sensor.py:124
Integration: Integration - Riemann sum integral sensor (documentation, issues)
First occurred: 7:25:00 PM (12 occurrences)
Last logged: 7:25:01 PM

Could not use last_valid_state

-----

Right now I'm using home-assistant-ingeteam-modbus v0.3.0 on Home Assistant Release 2023.10.5
(but I got not working it for several past releases and versions).

---
What else can I try??
Any idea how can I continue debugging this problem??

Thank you very much for your work and help.

**Comment by oscarrdg** [comment]
I'm getting this error, not sure if it's related:

Logger: homeassistant
Source: helpers/entity.py:1072
First occurred: 12:24:26 AM (1 occurrences)
Last logged: 12:24:26 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1181, in _async_registry_updated
    await self.async_remove()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1072, in async_remove
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.ingeteam_active_power async_remove called twice

**Comment by oscarrdg** [comment]
I had some helper sensor referencing some ingeteam sensor. I deleted it.

Doing more tests:
Deleting every ingeteam device and entity, restarting and adding again the new device:
I'm getting again the error:

---
Logger: homeassistant.components.integration.sensor
Source: components/integration/sensor.py:124
Integration: Integration - Riemann sum integral sensor (documentation, issues)
First occurred: 12:49:40 PM (12 occurrences)
Last logged: 12:49:40 PM

Could not use last_valid_state

---
Notably,  I'm seeing 12 sensors "unavailable". And the rest of sensors are "unknown".
That's explained by the 12 occurrences of the mentioned error.

But I still don't understand why the integration is not able to get data from the inverter, but it's not showing any "connection timeout" or similar error.

**Comment by oscarrdg** [comment]
Still doing some tests with this problem.
I have checked in the inverter that the modbus connection is stablished properly, and it's sending packets withouth errors:

![Selection_999(831)](https://github.com/vortizhe/home-assistant-ingeteam-modbus/assets/12894199/022aa086-d743-42f6-9e5f-ece7a9cc3797)

So, it seems there's no connection error but the information dont get processed properly by the integration?

What else could I test in order to debug what is happening?

**Comment by vortizhe** [comment]
Since Home Assistant version 2023.9.1 pymodbus was updated to match hass version, some users suffer this problem. Once there is a connection problem, the integration is unable to retrieve more data even if the connection is recovered.

I release a new version 0.3.2 with auto reconnections in case of modbus connectivity problems and improved logs to better debuggin.

**Comment by oscarrdg** [comment]
OMG!!
Updated to v0.3.2 and it works again!!

I'll do some more tests, but my first impression is that it's working perfectly again!

Thank you so much @vortizhe !

**Comment by oscarrdg** [comment]
Everything still working as expected, so I am going to close this issue.
Thanks again for your work!
